### ISSUE TITLE
Add REST API support for django-avatar

### ISSUE THREAD

**Issue by nebiyuelias1** [jazzband/django-avatar#185]
I have looked pretty much everywhere and I couldn't find any REST API support for this app. I think it should have one.

**Comment by johanneswilm** [comment]
@nebiyuelias1 I'll be happy to merge a PR if you come up with one

**Comment by the-vegetarian-vampire** [comment]
@johanneswilm thanks so much for all of this. I am lost at step 3 per: https://django-avatar.readthedocs.io/en/stable/. 

If I wanted to add the avatar to say: path("profile/<str:username>", views.profile, name="profile"),

Otherwise I have followed the documentation, and when I cick 'change avatar' on an html page, I get a ValueError: not enough values to unpack (expected 2, got 1).

Do I need to specify a new avatar.html page?

Thanks so much, your time is greatly appreciated.
